# Generated by Django 3.1 on 2020-11-11 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='article',
            new_name='post',
        ),
    ]
