# Generated by Django 3.1 on 2020-11-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0003_comments_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(max_length=1000),
        ),
    ]
